/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package additionneur2lenecjavachap6;

/**
 *
 * @author felix
 */
public class PanneauAddProf extends javax.swing.JPanel {

    /**
     * Creates new form PanneauAddProf
     */
    public PanneauAddProf() {
        initComponents();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelText1 = new javax.swing.JLabel();
        labelText2 = new javax.swing.JLabel();
        zoneText1 = new javax.swing.JTextField();
        zoneTexte2 = new javax.swing.JTextField();
        sortie = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 3, 2, 5));

        labelText1.setText("entrée 1 :");
        add(labelText1);

        labelText2.setText("entrée 2 :");
        add(labelText2);

        zoneText1.setText("jTextField1");
        zoneText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneText1ActionPerformed(evt);
            }
        });
        add(zoneText1);

        zoneTexte2.setText("jTextField2");
        add(zoneTexte2);

        sortie.setText("sortie");
        add(sortie);

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(20, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * si le bouton est cliqué
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // petit test
        String res = "resultat : ";
        float temp;
        temp = Float.parseFloat(this.zoneText1.getText());
        temp += Float.parseFloat(this.zoneTexte2.getText());
        res+=String.valueOf(temp);
        this.sortie.setText(res); // affiche du nouveau text aprés avoir cliqué
    }//GEN-LAST:event_jButton1ActionPerformed

    private void zoneText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneText1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelText1;
    private javax.swing.JLabel labelText2;
    private javax.swing.JLabel sortie;
    private javax.swing.JTextField zoneText1;
    private javax.swing.JTextField zoneTexte2;
    // End of variables declaration//GEN-END:variables
}
