/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author felix
 */
public class InterfacePannel extends javax.swing.JPanel {

    /**
     * Creates new form InterfacePannel
     */
    public InterfacePannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        soumettre = new javax.swing.JButton();
        vitesseAutorisee = new javax.swing.JTextField();
        vitesseUtilisateur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultAmmende = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nbPointsRetires = new javax.swing.JLabel();

        jLabel1.setText("vitesse autorisée max");

        jLabel2.setText("vitesse de l'utilisateur");

        soumettre.setBackground(new java.awt.Color(255, 153, 153));
        soumettre.setText("soumettre");
        soumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soumettreActionPerformed(evt);
            }
        });

        vitesseAutorisee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitesseAutoriseeActionPerformed(evt);
            }
        });

        vitesseUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitesseUtilisateurActionPerformed(evt);
            }
        });

        jLabel3.setText("ammende");

        resultAmmende.setBackground(new java.awt.Color(204, 255, 255));
        resultAmmende.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultAmmende.setText(" ");

        jLabel5.setText("points retirés");

        nbPointsRetires.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nbPointsRetires.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(soumettre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vitesseAutorisee, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vitesseUtilisateur)))
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nbPointsRetires, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(resultAmmende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitesseAutorisee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vitesseUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resultAmmende))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nbPointsRetires))
                .addGap(76, 76, 76)
                .addComponent(soumettre)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soumettreActionPerformed
        // TODO add your handling code here:
        int pointsNeg=0;
        int ammende=0;
        
        float vitesse = Float.parseFloat(this.vitesseUtilisateur.getText());
        float lavitesseMax = Float.parseFloat(this.vitesseAutorisee.getText());
        // différence de vitesse, infraction si positive ou normal si negative ou null
        float diff = vitesse-lavitesseMax;
        
        if (diff <= 20 && diff > 0 &&  lavitesseMax <= 50){
            if (lavitesseMax > 50){
                ammende = 68;             
            } else {
                ammende = 135;
            }
            pointsNeg = 1;      
        } else if (diff >= 20 && diff < 30){
            ammende = 135;
            pointsNeg = 2;
        } else if (diff >= 30 && diff <= 40){
            ammende = 135;
            pointsNeg = 3;
        } else if(diff >= 40 && diff < 50){
            ammende = 135;
            pointsNeg=4;
        } else if(diff >= 50){
            ammende = 1500;
            pointsNeg=6;
        }        
        this.resultAmmende.setText((ammende == 0) ? "aucune":String.valueOf(ammende)+"€");
        this.nbPointsRetires.setText((pointsNeg == 0) ? "aucun":String.valueOf(pointsNeg));
    }//GEN-LAST:event_soumettreActionPerformed
    
    private void vitesseAutoriseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitesseAutoriseeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitesseAutoriseeActionPerformed

    private void vitesseUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitesseUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitesseUtilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nbPointsRetires;
    private javax.swing.JLabel resultAmmende;
    private javax.swing.JButton soumettre;
    private javax.swing.JTextField vitesseAutorisee;
    private javax.swing.JTextField vitesseUtilisateur;
    // End of variables declaration//GEN-END:variables
}
